### ISSUE TITLE
`from_rgb888_components` seems broken

### ISSUE THREAD

**Issue by Lucky4Luuk** [LoganDark/rgb565#2]
Doing simply `from_rgb888_components(64, 128, 96)` and then calling `to_rgb888_components()` results in `57, 125, 90` instead of the expected result. I'd provide a code sample but this is all I do in the project anyway, so I doubt there's anything wrong there.

**Comment by LoganDark** [comment]
RGB565 has less precision than RGB888. This is intended.

If you put `57, 125, 90` into it in the first place though, it should be represented exactly and returned back unchanged.

**Comment by Lucky4Luuk** [comment]
Its true it has less precision, however can't RGB565 perfectly represent all 3 numbers? 64, 128 and 96 all divide perfectly by 8, and if you do `(64 * 5) / 8`, and then reverse that again (`(40 * 8) / 5` then you get 64 again (of course doing integer math). As far as I can tell, the values I picked should not change by converting them back and forth

**Comment by Lucky4Luuk** [comment]
Sorry, I wrote that comment too fast, I don't think the math there was necessarily correct. But I just did my own implementation of RGB565 during my lunch break, and all I do is shift the R and B channels right by 3, and the G channel right by 2, and then the other way for decoding, and it works perfectly fine and I end up with my original numbers back as well, and other numbers work fine too. I genuinely think there might be an issue with your LUT.

**Comment by LoganDark** [comment]
This crate tests every single rgb565 value (entire 16 bit space) for rgb roundtrips. The difference with this crate is that it lets the maximum value map to 255 instead of something like 248. That's probably the discrepancy you are seeing
